from dataclasses import dataclass
from pathlib import Path
from typing import Any

@dataclass(frozen=True)
class CameraSpec:
    name: str = ...
    index: int | None = ...
    device: str | None = ...
    intrinsics_file: str | None = ...
    mapping_file: str | None = ...

@dataclass(frozen=True)
class Config:
    camera_backend: str = ...
    vision_backend: str = ...
    target_fps: int = ...
    camera_index: int | None = ...
    camera_device: str | None = ...
    cameras: tuple[CameraSpec, ...] | None = ...
    fusion_enable: bool = ...
    fusion_method: str = ...
    fusion_max_merge_dist_m: float = ...
    fusion: dict[str, Any] | None = ...
    exclude_marker_ids: list[int] | None = ...
    allowed_marker_ids: list[int] | None = ...
    record_video: str | None = ...
    record_jsonl: str | None = ...
    object_timeout_s: float = ...
    metrics_host: str = ...
    metrics_port: int = ...
    ws_host: str = ...
    ws_port: int = ...
    profile: str | None = ...
    intrinsics_file: str | None = ...
    mapping_file: str | None = ...
    zones_file: str | None = ...
    analytics_out_dir: str | None = ...
    source_mode: str = ...
    replay_input: str | None = ...
    replay_speed: float = ...
    replay_loop: bool = ...
    runs_dir: str | None = ...
    health: dict[str, Any] | None = ...
    timing: dict[str, Any] | None = ...
    compute: dict[str, Any] | None = ...
    faults: dict[str, Any] | None = ...

@dataclass(frozen=True)
class CameraCalibPaths:
    name: str
    cam_dir: Path
    intrinsics: Path | None
    mapping: Path | None

@dataclass(frozen=True)
class CalibPaths:
    profile: str
    profile_dir: Path
    anchors: Path
    zones: Path
    mapping: Path
    test_points: Path
    intrinsics: Path | None = ...
    cameras: tuple[CameraCalibPaths, ...] | None = ...

def load_config(path: Path) -> Config: ...
def load_active_profile(active_profile_path: Path = ...) -> str | None: ...
def resolve_profile(profile: str | None, *, active_profile_path: Path = ...) -> str | None: ...
def resolve_profile_dir(
    profile: str | None,
    *,
    calib_root: Path = ...,
    active_profile_path: Path | None = ...,
    strict: bool = ...,
) -> Path | None: ...
def maybe_get_calib_paths(
    profile: str | None,
    *,
    calib_root: Path = ...,
    active_profile_path: Path | None = ...,
) -> CalibPaths | None: ...
def apply_profile_defaults(cfg: Config, *, calib_root: Path = ...) -> Config: ...
